import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { initReddio } from "./utils/config";

const Home: NextPage = () => {
  initReddio()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SDK Examples!
        </h1>

        <div className={styles.grid}>
          <Link href="/process1">
            <a className={styles.card}>
              <h2>流程 1 &rarr;</h2>
              <p>Deposit/Transfer/Withdraw ETH between L1 and L2.</p>
            </a>
          </Link>

          <Link href="/process2">
            <a className={styles.card}>
              <h2>流程 2 &rarr;</h2>
              <p>Deposit/Transfer/Withdraw ERC20 between L1 and L2.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
